### ISSUE TITLE
Forgot password email should be fully configurable

### ISSUE THREAD

**Issue by ComLock** [enonic/app-simple-idprovider#5]
Some customers need the email to be in Norwegian.

I guess the simplest solution would be a text area.

Perhaps with some placeholders like ${displayName} ${email}

**Comment by sigdestad** [comment]
This should be handled with translations in the app directly imho

**Comment by ComLock** [comment]
But then you cannot simply use the app from market... unless you pre translated all languages.
And still it would not be possible to customize the email...

**Comment by sigdestad** [comment]
True..

**Comment by sigdestad** [comment]
We will rather solve this using a planned tool for "localization" of apps
